name: Build Sentinel

on:
  workflow_call:
    inputs:
      HEROKU_APP_NAME:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - run: heroku git:remote -a ${{ inputs.HEROKU_APP_NAME }}
      # - run: git remote add heroku https://git.heroku.com/${{ inputs.HEROKU_APP_NAME }}.git
      # - run: git remote add heroku https://git.heroku.com/obscure-waters-39652.git
      - run: git remote add heroku git@heroku.com:obscure-waters-39652.git
      - run: git push heroku develop:master
      # - uses: akhileshns/heroku-deploy@v3.11.10
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: ${{ inputs.HEROKU_APP_NAME }}
      #     heroku_email: "quinnstoltz@gmail.com"
      #     dontautocreate: true
