name: dev-push

on:
  push:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  deploy:
    # uses: ./.github/workflows/deploy.yml
    # with:
    #   HEROKU_APP_NAME: 'obscure-waters-216544'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: obscure-waters-216544
      #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: obscure-waters-216544
          # branch: develop
          buildpacks: ['https://github.com/moneymeets/python-poetry-buildpack.git', 'heroku/python']
